# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :metrics do

    scan(scheme: "Marvel", 
      code_coverage: true, 
      derived_data_path: "./DerivedData", 
      output_directory: "./sonar-reports",
      devices: "iPhone 6s")
     
    slather(cobertura_xml: true, 
      jenkins: true, 
      scheme: "Marvel", 
      build_directory: "./DerivedData", 
      output_directory: "./sonar-reports", 
      proj: "./Marvel.xcodeproj")

     swiftlint(output_file: "./sonar-reports/swiftlint.txt", 
      ignore_exit_status: true)

     sonar
end
end